{{- if .Values.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.tokensSecret }}
  labels:
    {{- include "scrim.labels" . | nindent 4 }}
spec:
  itemPath: "vaults/{{ .Values.onePassword.vault }}/items/{{ .Values.onePassword.tokensItem }}"
{{- if .Values.hub.oidc.issuer }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.oidcSecret }}
  labels:
    {{- include "scrim.labels" . | nindent 4 }}
spec:
  itemPath: "vaults/{{ .Values.onePassword.vault }}/items/{{ .Values.onePassword.oidcItem }}"
{{- end }}
{{- end }}
